# baseURL = 'https://geekifan.github.io/zero-academic-page-starter/'
baseURL = 'https://wzhang.github.io'
title = 'Weijia Zhang | Academic Homepage'

# multi-language support
defaultContentLanguage = 'en'

# enable git info
enableGitInfo = true

# disable taxonomy, term and RSS (which removes categories, tags and index.xml)
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Zero'

    [languages.en.params]
      author = "Weijia Zhang"
      description = "Ph.D. in AI, HKUST"
      motto = "Keep your eyes on the stars, and your feet on the ground."
    
    [[languages.en.menu.main]]
      name = 'About Me'
      url = '#about-me'
      weight = 1
    [[languages.en.menu.main]]
      name = 'News'
      url = '#news'
      weight = 2
    [[languages.en.menu.main]]
      name = 'Publications'
      url = '#publications'
      weight = 3
    [[languages.en.menu.main]]
      name = 'Awards'
      url = '#honors-and-awards'
      weight = 4
    [[languages.en.menu.main]]
      name = 'Services'
      url = '#services'
      weight = 4

      
[params] 
  customCSS = ["css/custom.css"]
  profilePicture = "/images/profile_weijia.png"
  enableDarkMode = true
  footer = """Built with <a href='https://gohugo.io/' target='_blank'>Hugo</a> using the 
<a href='https://github.com/geekifan/zero-academic-page' target='_blank'>Zero Academic Page</a> theme. Hosted on <a href='https://pages.github.com/' target='_blank'>GitHub Pages</a>."""
  copyright = "© Weijia Zhang"

   [[params.social]]
    name = "email"
    url = "vegazhang3@gmail.com"
    icon = "fas fa-envelope"
    description = "Email"

  [[params.social]]
    name = "google-scholar"
    url = "https://scholar.google.com/citations?user=lSi3CIoAAAAJ"
    icon = "fab fa-google-scholar"
    description = "Google Scholar"
    

[build]
  writeStats = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
